version: "3.9"

services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - wiremock

